int readCommand(int, int);
char *readResult(int);
void sampleReturn(int, char);
void passCommand(int);
int newBoard(int);
int saveGame(char*);
int loadGame(char*);
void sendBoard(int);
void readBoard(int);
int checkWin(int);
int checkWinServerEnd();
int isMoveValid(int);
int moveTile(int);
int getMoveValidity(int, int);
